#' Download Modis images from search function response
#'
#' \code{modDownSearch} downloads the images from a list of urls generated by the \code{modSearch} function 
#' from NASA’s EartData plataform.
#'
#' \code{modDownSearch} is able to download Modis Terra and Aqua products.
#' These products are published in the \href{https://earthdata.nasa.gov}{Earth Data Platform}. The platform
#' is supported by the Earth Observing System Data and Information System (EODIS)
#' and managed NASA’s Earth Science Data Systems (ESDS).
#' \code{modDownSearch} requires the credentianls from EarthData to access the NASA’s web data service.
#' \href{https://urs.earthdata.nasa.gov/users/new}{Get your credentials}.
#'
#' @param searchres the output of the \code{\link{modSearch}} function.
#' @param username login credentials to access the NASA’s EarthData web service.
#' @param password  login credentials to access the NASA’s EarthData web service.
#' @param overwrite logical argument. If \code{TRUE} overwrites the existing images with the same name.
#' @param ... argument to allow function nestering:
#' \itemize{
#'   \item \code{AppRoot} root directory where the images will be saved.
#' }
#'
#' @examples
#' \dontrun{
#' # load a spatial polygon object of Navarre
#' data(ex.navarre)
#' mList <- modSearch(product = "MYD13A2",
#'                    startDate = as.Date("01-01-2011", "%d-%m-%Y"),
#'                    endDate = as.Date("31-12-2013", "%d-%m-%Y"),
#'                    collection = 6,
#'                    extent = ex.navarre)
#' head(mList)
#' # download first image in mList
#' modDownSearch(mList[1], "user", "pass")
#' # download all images in mList
#' modDownSearch(mList, "user", "pass")
#' }
modDownSearch<-function(searchres ,username = NULL,password = NULL,overwrite=FALSE,...){
  arg<-list(...)
  if(is.null(username)|is.null(password)){
    stop("Username and/or password not defined!")
  }
  AppRoot<-defineAppRoot(...)
  dir.create(AppRoot,showWarnings = F,recursive = T)
  for(l in searchres){
    if(file.exists(paste0(AppRoot,"/",basename(l)))&&overwrite){
      file.remove(paste0(AppRoot,"/",basename(l)))
    }

    if(!file.exists(paste0(AppRoot,"/",basename(l)))){
      c.handle = new_handle()
      handle_setopt(c.handle,
                    referer=paste0("https://",domain(l),"/"),
                    useragent = getRGISToolsOpt("USERAGENT"),
                    followlocation = TRUE ,
                    autoreferer = TRUE ,
                    username=username,
                    password=password)
      print(paste0("Downloading ",basename(l)," image."))
      curl_download(l, destfile=paste0(AppRoot,"/",basename(l)),handle = c.handle)
    }else if(overwrite){
      c.handle = new_handle()
      handle_setopt(c.handle,
                    referer=paste0("https://",domain(l),"/"),
                    useragent = getRGISToolsOpt("USERAGENT"),
                    followlocation = TRUE ,
                    autoreferer = TRUE ,
                    username=username,
                    password=password)
      file.remove(paste0(AppRoot,"/",basename(l)))
      print(paste0("Downloading ",basename(l)," image."))
      curl_download(l, destfile=paste0(AppRoot,"/",basename(l)),handle = c.handle)
    }else{
      message("File already exists.")
    }
  }
  message(paste0("The images have been downloaded and saved on HDD. \nFile path: ",AppRoot))
}

